# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_video = QtWidgets.QPushButton(self.centralwidget)
        self.Button_video.setGeometry(QtCore.QRect(60, 610, 131, 41))
        self.Button_video.setObjectName("Button_video")
        self.Button_start = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start.setGeometry(QtCore.QRect(360, 610, 131, 41))
        self.Button_start.setObjectName("Button_start")
        self.Button_line = QtWidgets.QPushButton(self.centralwidget)
        self.Button_line.setGeometry(QtCore.QRect(640, 610, 111, 41))
        self.Button_line.setObjectName("Button_line")
        self.Button_signal = QtWidgets.QPushButton(self.centralwidget)
        self.Button_signal.setGeometry(QtCore.QRect(870, 610, 101, 41))
        self.Button_signal.setObjectName("Button_signal")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(24, 25, 1051, 561))
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.Button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stop.setGeometry(QtCore.QRect(60, 680, 131, 41))
        self.Button_stop.setObjectName("Button_stop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 26))
        self.menubar.setObjectName("menubar")
        self.menuggg = QtWidgets.QMenu(self.menubar)
        self.menuggg.setObjectName("menuggg")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionscreen1 = QtWidgets.QAction(MainWindow)
        self.actionscreen1.setObjectName("actionscreen1")
        self.menuggg.addAction(self.actionscreen1)
        self.menubar.addAction(self.menuggg.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_video.setText(_translate("MainWindow", "Video"))
        self.Button_start.setText(_translate("MainWindow", "Start"))
        self.Button_line.setText(_translate("MainWindow", "Line"))
        self.Button_signal.setText(_translate("MainWindow", "Signal"))
        self.Button_stop.setText(_translate("MainWindow", "Stop"))
        self.menuggg.setTitle(_translate("MainWindow", "ggg"))
        self.actionscreen1.setText(_translate("MainWindow", "screen1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
